services:
  - type: web
    name: world264-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: LINE_GROUP_IDS
        sync: false
      - key: TZ
        value: Asia/Bangkok
